management:
  server:
    port: 9090
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /api/actuator

springdoc:
  swagger-ui:
    enabled: false

logging:
  level:
    root: INFO
    io.github.resilience4j: INFO
    com.weather.weather_api: INFO
    org.springframework.security: WARN