logging:
  level:
    root: INFO
    io.github.resilience4j: INFO
    com.weather.weather_api: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
