spring:
  profiles:
    group:
      local: "local"
  management:
    server:
      port: 8083
      address: 127.0.0.1

  aop:
    proxy-target-class: true
    auto: true
  application:
    name: weather-api
  cache:
    type: caffeine
    cache-names: forecastCache
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=15m

project:
  version: v1

weatherapi:
  i18n:
    enabled: true
#    locale: en_US
  provider:
    geocoding:
      defaultProvider: nominatim
      nominatim:
        baseurl: "https://nominatim.openstreetmap.org/search"
    forecast:
      defaultProvider: open_meteo
      meteo:
        baseurl: "https://api.open-meteo.com/v1/forecast"

resilience4j:
  retry:
    instances:
      geocodeRetry:
        maxAttempts: 3
        waitDuration: 2s
      forecastRetry:
        maxAttempts: 3
        waitDuration: 2s

metrics:
  auth:
    enabled: false

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG
    com.weather.weather_api: DEBUG
