spring:
  application:
    name: weather-api

project:
  version: v1

server:
  port: 8082
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG
    com.weather.weather_api: DEBUG
