name: Release (main → tag)

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '21' }

      - name: Build & test
        run: mvn -B clean verify

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install semantic-release
        run: npm i -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/exec @semantic-release/github conventional-changelog-conventionalcommits

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Versão estável X.Y.Z, cria tag vX.Y.Z e GitHub Release
      - name: semantic-release (main)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: semantic-release
