name: Release deploy (Railway)

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build & test (Maven)
        run: mvn -B clean verify

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weather-api-jar
          path: target/*.jar

      - name: Setup Node (Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm i -g @railway/cli@latest

      - name: Show Railway CLI version
        run: railway --version

      - name: Set APP_VERSION in Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          railway variables set APP_VERSION="$VERSION" \
            --project "${{ secrets.RAILWAY_PROJECT_ID }}" \
            --service "${{ secrets.RAILWAY_SERVICE_ID }}"

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up \
            --project "${{ secrets.RAILWAY_PROJECT_ID }}" \
            --service "${{ secrets.RAILWAY_SERVICE_ID }}" \
            --ci
